# Data Preprocessing

The goal of this lab is to introduce you to data preprocessing techniques in order to make your data suitable for applying a learning algorithm.

## 1. Handling Missing Values

A common (and very unfortunate) data property is the ocurrence of missing and erroneous values in multiple features in datasets. For this exercise we will be using a data set about abalone snails.
The data set is contained in the Zip file you downloaded from Moodle.

To determine the age of a abalone snail you have to kill the snail and count the annual
rings. You are told to estimate the age of a snail on the basis of the following attributes:
1. type: male (0), female (1) and infant (2)
2. length in mm
3. width in mm
4. height in mm
5. total weight in grams
6. weight of the meat in grams
7. drained weight in grams
8. weight of the shell in grams
9. number of annual rings (number of rings +1, 5 yields age)

However, the data is incomplete. Missing values are marked with −1.

In [2]:
import pandas as pd
import numpy as np

# load data 
df = pd.read_csv("http://www.cs.uni-potsdam.de/ml/teaching/ss15/ida/uebung02/abalone.csv")
df.columns=['type','length','width','height','total_weight','meat_weight','drained_weight','shell_weight','num_rings']
df.head()

,type,length,width,height,total_weight,meat_weight,drained_weight,shell_weight,num_rings
0,0,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,-1
1,1,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
2,0,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
3,2,-1.000,0.255,0.080,0.2050,0.0895,0.0395,0.055,7
4,2,0.425,0.300,0.095,0.3515,0.1410,0.0775,0.120,8

### Exercise 1.1

Compute the mean of of each numeric column and the counts of each categorical column, excluding the missing values.

In [2]:
##################
#INSERT CODE HERE#
##################

mean_col = df.replace(-1,np.nan).mean()
print(mean_col)

#print(len(pd.unique(df['num_rings'])))

print("'type' Categorical column\n")
print(df['type'].replace(-1,np.nan).value_counts())

print("\n'num_rings' Categorical column\n")
print(df['num_rings'].replace(-1,np.nan).value_counts())

type              0.953534
length            0.523692
width             0.407955
height            0.139610
total_weight      0.828843
meat_weight       0.359263
drained_weight    0.180249
shell_weight      0.238604
num_rings         9.921756
dtype: float64
'type' Categorical column

0.0    1500
2.0    1310
1.0    1279
Name: type, dtype: int64

'num_rings' Categorical column

9.0     667
10.0    614
8.0     560
11.0    477
7.0     382
6.0     258
12.0    256
13.0    201
14.0    121
5.0     112
15.0    101
16.0     65
4.0      57
17.0     57
18.0     40
19.0     32
20.0     25
3.0      15
21.0     14
23.0      8
22.0      6
24.0      2
27.0      2
29.0      1
1.0       1
25.0      1
26.0      1
2.0       1
Name: num_rings, dtype: int64

### Exercise 1.2

Compute the median of each numeric column,  excluding the missing values.

In [9]:
##################
#INSERT CODE HERE#
##################

median_col = df.replace(-1,np.nan).median()
print(median_col)

type              1.00000
length            0.54500
width             0.42500
height            0.14000
total_weight      0.80175
meat_weight       0.33600
drained_weight    0.17050
shell_weight      0.23350
num_rings         9.00000
dtype: float64

### Exercise 1.3

Handle the missing values in a way that you find suitable. Argue your choices.

In [9]:
##################
#INSERT CODE HERE#
##################

#check how many missing vlaues each column has 
print((df==-1).sum())
new_df = df.replace(-1, np.nan)
#pd.set_option('display.max_rows', 4176)
#print(new_df)
#print((new_df==-1).sum())

# Type and num_rings are categorical value, so use mode of this two columns
new_df['type'] = new_df['type'].fillna(new_df['type'].mode().iloc[0])
new_df['num_rings'] = new_df['num_rings'].fillna(new_df['num_rings'].mode().iloc[-1])
#print(new_df)

# other columns are replaced by the mean of each column
new_df = new_df.fillna(new_df.mean())

new_df.head(10)

type               87
length            124
width             124
height            124
total_weight      106
meat_weight       125
drained_weight    109
shell_weight      102
num_rings          99
dtype: int64

,type,length,width,height,total_weight,meat_weight,drained_weight,shell_weight,num_rings
0,0.0,0.350000,0.265,0.090,0.2255,0.0995,0.0485,0.070000,9.0
1,1.0,0.530000,0.420,0.135,0.6770,0.2565,0.1415,0.210000,9.0
2,0.0,0.440000,0.365,0.125,0.5160,0.2155,0.1140,0.155000,10.0
3,2.0,0.523692,0.255,0.080,0.2050,0.0895,0.0395,0.055000,7.0
4,2.0,0.425000,0.300,0.095,0.3515,0.1410,0.0775,0.120000,8.0
5,1.0,0.530000,0.415,0.150,0.7775,0.2370,0.1415,0.330000,20.0
6,1.0,0.545000,0.425,0.125,0.7680,0.2940,0.1495,0.260000,16.0
7,0.0,0.475000,0.370,0.125,0.5095,0.2165,0.1125,0.165000,9.0
8,1.0,0.550000,0.440,0.150,0.8945,0.3145,0.1510,0.320000,19.0
9,1.0,0.523692,0.380,0.140,0.6065,0.1940,0.1475,0.238604,14.0

### Exercise 1.4

Perform Z-score normalization on every column (except the type of course!)

In [11]:
from scipy import stats

z_score = df.loc[ :, df.columns != 'type'].apply(stats.zscore)
z_score.head(10)

,length,width,height,total_weight,meat_weight,drained_weight,shell_weight,num_rings
0,-0.451527,-0.391702,-0.079751,-0.990125,-0.686952,-0.465375,-0.587604,-2.965564
1,0.181217,0.208544,0.147804,-0.187423,-0.194650,-0.036616,0.007003,-0.184349
2,-0.135155,-0.004447,0.097236,-0.473658,-0.323213,-0.163400,-0.226593,0.093773
3,-5.197109,-0.430428,-0.130318,-1.026571,-0.718309,-0.506868,-0.651312,-0.740592
4,-0.187884,-0.256163,-0.054467,-0.766115,-0.556821,-0.331676,-0.375245,-0.462470
5,0.181217,0.189181,0.223655,-0.008749,-0.255796,-0.036616,0.516666,2.874988
6,0.233946,0.227907,0.097236,-0.025639,-0.077062,0.000266,0.219363,1.762502
7,-0.012122,0.014916,0.097236,-0.485214,-0.320077,-0.170315,-0.184121,-0.184349
8,0.251522,0.285995,0.223655,0.199260,-0.012781,0.007182,0.474194,2.596866
9,-5.197109,0.053642,0.173088,-0.312762,-0.390630,-0.008955,-5.132103,1.206259

## 2. Preprocessing text (Optional)

One possible way to transform text documents into vectors of numeric attributes is to use the TF-IDF representation. We will experiment with this representation using the 20 Newsgroup data set. The data set contains postings on 20 different topics. The classification problem is to decide which of the topics a posting falls into. Here, we will only consider postings about medicine and space.

In [9]:
from sklearn.datasets import fetch_20newsgroups


categories = ['sci.med', 'sci.space']
raw_data = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42)
print(f'The index of each category is: {[(i,target) for i,target in enumerate(raw_data.target_names)]}')

The index of each category is: [(0, 'sci.med'), (1, 'sci.space')]

Check out some of the postings, might find some funny ones!

In [10]:
import numpy as np
idx = np.random.randint(0, len(raw_data.data))
print (f'This is a {raw_data.target_names[raw_data.target[idx]]} email.\n')
print (f'There are {len(raw_data.data)} emails.\n')
print(raw_data.data[idx])

This is a sci.med email.

There are 1187 emails.

From: jim.zisfein@factory.com (Jim Zisfein)
Subject: Post Polio Syndrome Information Needed Please !!!
Distribution: world
Organization: Invention Factory's BBS - New York City, NY - 212-274-8298v.32bis
Reply-To: jim.zisfein@factory.com (Jim Zisfein)
Lines: 67

KS> From: keith@actrix.gen.nz (Keith Stewart)
KS>My wife has become interested through an acquaintance in Post-Polio Syndrome
KS>This apparently is not recognised in New Zealand and different symptons ( eg
KS>chest complaints) are treated separately. Does anone have any information

I'm not sure that this condition is "recognised" anywhere (in the
sense of a disease with diagnostic criteria, clear boundaries
between it and other diseases, unique pathologic or physiologic
features, etc), but here goes with what many neurologists agree on.

Post-polio syndrome patients have evidence of motor neuron disease
by clinical examination, EMG, and muscle biopsy.  The abnormalities
are mostly chronic (due to old polio) but there is evidence of
ongoing deterioration.  Clinically, the patients complain of
declining strength and endurance with everyday motor tasks.
Musculoskeletal pain is a nearly universal feature that doubtless
contributes to the impaired performance.  The examination shows
muscle weakness and atrophy.  The EMG shows evidence of old
denervation with reinnervation (giant and long-duration motor unit
action potentials) *and* evidence of active denervation
(fibrillation potentials).  The biopsy also shows old denervation
with reinnervation (fiber-type grouping) *and* evidence of active
denervation (small, angulated fibers with dense oxidative enzyme
staining) - but curiously, little or no group atrophy.

Post-polio patients do not have ALS.  In ALS, there is clinically
evident deterioration from one month to the next.  In post-polio,
the patients are remarkably stable in objective findings from one
year to the next.  Of course, there are patients who had polio
before who develop genuine ALS, but ALS is no more common among
polio survivors than among people who never had polio.

The cause of post-polio syndrome is unknown.  There is little
evidence that post-polio patients have active polio virus or
destructive immunologic response to virus antigen.

There is no solid evidence that patients with post-polio have
anything different happening to the motor unit (anterior horn cells,
motor axons, neuromuscular junctions, and muscle fibers) than
patients with old polio who are not complaining of deterioration.
Both groups can have the same EMG and biopsy findings.  The reason
for these "acute" changes in a "chronic" disease (old polio) is
unknown.  Possibly spinal motor neurons (that have reinnervated huge
numbers of muscle fibers) start shedding the load after several
years.

There are a couple of clinical features that distinguish post-polio
syndrome patients from patients with old polio who deny
deterioration.  The PPS patients are more likely to have had severe
polio.  The PPS patients are *much* more likely to complain of pain.
They also tend to score higher on depression scales of
neuropsychologic tests.

My take on this (I'm sure some will disagree):  after recovery from
severe polio there can be abnormal loading on muscles, tendons,
ligaments, bones, and joints, that leads to inflammatory and/or
degenerative conditions affecting these structures.  The increasing
pain, superimposed on the chronic (but unchanging) weakness, leads
to progressive impairment of motor performance and ADL.  I am
perhaps biased by personal experience of having never seen a PPS
patient who was not limited in some way by pain.  I do not believe
that PPS patients have more rapid deterioration of motor units than
non-PPS patients (i.e., those with old polio of similar severity but
without PPS complaints).
---
 . SLMR 2.1 . E-mail: jim.zisfein@factory.com (Jim Zisfein)

Lets pick the first 10 postings from each category

In [11]:
idxs_med = np.flatnonzero(raw_data.target == 0)
idxs_space = np.flatnonzero(raw_data.target == 1)
idxs = np.concatenate([idxs_med[:10],idxs_space[:10]])
data = np.array(raw_data.data)
data = data[idxs]

<a href="http://www.nltk.org/">NLTK</a> is a toolkit for natural language processing. Take some time to install it and go through this <a href="http://www.slideshare.net/japerk/nltk-in-20-minutes">short tutorial/presentation</a>.

The downloaded package below is a tokenizer that divides a text into a list of sentences, by using an unsupervised algorithm to build a model for abbreviation words, collocations, and words that start sentences.

In [12]:
import nltk
import itertools
nltk.download('punkt')

# Tokenize the sentences into words
tokenized_sentences = [nltk.word_tokenize(sent) for sent in data]
vocabulary_size = 1000
unknown_token = 'unknown'

[nltk_data] Downloading package punkt to C:\Users\SAFIAL ISLAM
[nltk_data]     AYON\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [13]:
# Count the word frequencies
word_freq = nltk.FreqDist(itertools.chain(*tokenized_sentences))
print (f"Found {len(word_freq.items())} unique words tokens.")

Found 1636 unique words tokens.

In [14]:
# Get the most common words and build index_to_word and word_to_index vectors
vocab = word_freq.most_common(vocabulary_size-1)
index_to_word = [x[0] for x in vocab]
index_to_word.append(unknown_token)
word_to_index = dict([(w,i) for i,w in enumerate(index_to_word)])
 
print (f"Using vocabulary size {vocabulary_size}." )
print (f"The least frequent word in our vocabulary is '{vocab[-1][0]}' and appeared {vocab[-1][1]} times.")

Using vocabulary size 1000.
The least frequent word in our vocabulary is 'AN' and appeared 1 times.

### Exercise 2.1

Code your own TF-IDF representation function and use it on this dataset. (Don't use code from libraries. Build your own function with Numpy/Pandas). Use the formular TFIDF = TF * (IDF+1). The effect of adding “1” to the idf in the equation above is that terms with zero idf, i.e., terms that occur in all documents in a training set, will not be entirely ignored. The term frequency is the raw count of a term in a document. The inverse document frequency is the natural logarithm of the inverse fraction of the documents that contain the word.

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
countvec = CountVectorizer()
df = pd.DataFrame(countvec.fit_transform(data).toarray(), columns=countvec.get_feature_names())

def tfidf(df):
    
    ##################
    #INSERT CODE HERE#
    ##################
    
    documents = len(df.index)
    tf = df.sum(axis = 0)
    idf = documents/df[df>0].count()
    tf_idf = tf * (idf + 1)
    return tf_idf
    
    
    
rep = tfidf(df)

# Check if your implementation is correct
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(norm=None, smooth_idf=False, use_idf=True)
X_train = pd.DataFrame(vectorizer.fit_transform(data).toarray(), columns=countvec.get_feature_names())
answer=['No','Yes']
epsilon = 0.0001
if rep is not None:
    print (f'Is this implementation correct?\nAnswer: {answer[1*np.all((X_train - rep) < epsilon)]}')

Is this implementation correct?
Answer: Yes